routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\ControllerListe;
use App\Http\Controllers\DesignSystemController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\TypeRecipeController;

use App\Http\Controllers\EnfantController;
use App\Http\Controllers\EtapeController;


use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/dashboard', function () {
    return redirect()->route('profile.edit');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::resource('type_recipe', TypeRecipeController::class);


Route::resource('recipe', RecipeController::class);


Route::resource('designsystem', DesignSystemController::class);

Route::resource('contact', ContactController::class);





Route::middleware('auth')->group(function () {
    Route::resource('enfant', EnfantController::class);
    Route::resource('etape', EtapeController::class);
    //Route::post('/etape/{id}', [EtapeController::class, 'show']);

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';

app/Models/Enfant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Enfant extends Model
{
    use HasFactory;


    protected $table = 'enfants';

    protected $fillable = [
        'name','profile_image','age','avatar_id'
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }


    public function avatar(){
        return $this->belongsTo(Avatar::class);
    }
}

app/Http/Controllers/EnfantController.php
<?php

namespace App\Http\Controllers;

use App\Models\Enfant;
use Illuminate\Support\Facades\Auth;
use App\Models\Avatar;

use Illuminate\Http\Request;
use App\Http\Requests\EnfantRequest;


class EnfantController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //

        $user = auth()->user(); // Récupérer l'utilisateur connecté
        $enfants = $user->enfants()->paginate(5); // Récupérer les enfants du user connecté
        return view('enfants.index', compact('enfants'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        $avatars = Avatar::all(); // Récupérer tous les avatars
        return view('enfants.create', compact('avatars'));

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(EnfantRequest $request)
    {
        //
        $user = Auth::user(); // Récupérer l'utilisateur connecté

        // Créer un nouvel enfant avec les données validées du formulaire et l'ID de l'utilisateur connecté
        $enfant = new Enfant($request->validated());
        $enfant->user_id = $user->id;
        $enfant->save();

        return redirect()->route('enfant.index')->with('ok', __('Enfant has been saved'));
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
        $avatars = Avatar::all(); // Récupérer tous les avatars

        $enfant = Enfant::findOrFail($id);
        return view('enfants.show', ['enfant' => $enfant,'avatars' => $avatars]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Enfant $enfant)
    {
        $avatars = Avatar::all(); // Récupérer tous les avatars
        return view('enfants.edit', ['enfant' => $enfant, 'avatars' => $avatars]);

        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(EnfantRequest $request, Enfant $enfant)
    {
        //
        $enfant->update($request->all());
        return redirect()->route('enfant.index')
            ->with('ok', __('Enfant has been updated'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Enfant $enfant)
    {
        //
        $enfant->delete();
        return response()->json();
    }
}

resources/views/enfants/create.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un enfant</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">

<div class="min-h-screen flex items-center justify-center">
    <div class="bg-white p-8 rounded-lg shadow-lg max-w-xl"> <!--  la taille de la card -->
        <form method="POST" action="{{ route('enfant.store') }}">
            @csrf
            <div class="mb-6 border-gray-600"> <!-- la marge entre les éléments -->
                <label for="name" class="block text-sm font-medium text-gray-700 ">Nom enfant</label>
                <input type="text" name="name" id="name" value="" required
                       class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-600 rounded-md">
            </div>
            <div class="mb-6 border-gray-600"> <!-- la marge entre les éléments -->
                <label for="age" class="block text-sm font-medium text-gray-700 ">Âge</label>
                <input type="number" name="age" id="age" value="" required
                       class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-600 rounded-md">
            </div>

        <div class="mb-6"> <!--la marge entre les éléments -->
                <label class="block text-sm font-medium text-gray-700">Avatar</label>
                <div class="flex space-x-6"> <!-- l'espace entre les images -->
                        @foreach($avatars as $avatar)
                        <label class="flex items-center">
                                <input type="radio" name="avatar_id" value="{{ $avatar->id }}" required class="focus:ring-blue-500  text-blue-600 border-gray-300"> <!-- Augmentation de la taille de la radio -->
                                <div class="h-16 w-16 flex justify-center items-center  rounded-full border-2 border-gray-300"> <!-- Définition du conteneur pour l'image -->
                                <img src="{{ asset($avatar->fichier) }}" alt="{{ $avatar->nom }}"
                                        class="object-contain object-center h-full w-full"> <!-- Redimensionnement et centrage de l'image -->
                                </div>
                        </label>
                        @endforeach
                </div>
        </div>

            <button type="submit"
                    class="w-full px-4 py-2 bg-blue-500 border border-transparent rounded-md font-semibold text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-100">
                Ajouter cet enfant
            </button>
        </form>
    </div>
</div>

</body>
</html>

resources/views/enfants/edit.blade.php
<form method="POST" action="{{ route('enfant.update', $enfant->id) }}">
        @csrf
        @method('PUT')
        <div class="mb-6 border-gray-600">
                <label for="name" class="block text-sm font-medium text-gray-700">Nom enfant</label>
                <input type="text" name="name" id="name" value="{{ $enfant->name }}" required
                        class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-600 rounded-md">
        </div>

        <div class="mb-6 border-gray-600">
                <label for="age" class="block text-sm font-medium text-gray-700">Âge</label>
                <input type="number" name="age" id="age" value="{{ $enfant->age }}" required
                        class="mt-1 focus:ring-blue-500 focus:border-blue-500 block w-full shadow-sm sm:text-sm border-gray-600 rounded-md">
        </div>

        <div class="mb-6">
                <label class="block text-sm font-medium text-gray-700">Avatar</label>
                <div class="flex flex-wrap gap-4">
                        @foreach($avatars as $avatar)
                        <label class="flex items-center">
                                <input type="radio" name="avatar_id" value="{{ $avatar->id }}" required
                                        class="focus:ring-blue-500 text-blue-600 border-gray-300" {{ $enfant->avatar_id
                                == $avatar->id ? 'checked' : '' }}>
                                <div
                                        class="h-16 w-16 flex justify-center items-center rounded-full border-2 border-gray-300">
                                        <img src="{{ asset($avatar->fichier) }}" alt="{{ $avatar->nom }}"
                                                class="object-cover object-center h-full w-full rounded-full">
                                </div>
                        </label>
                        @endforeach
                </div>
        </div>


        <button type="submit"
                class="w-full px-4 py-2 bg-blue-500 border border-transparent rounded-md font-semibold text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-100">
                Valider
        </button>
</form>

resources/views/enfants/index.blade.php
@extends('layouts.base')

@section('content')
<div class="container mx-auto px-4">
    <p class="text-5xl  font-bold my-8 text-center">Mes enfants</p>

    <div class=" flex flew-row flex-wrap items-center justify-center text-center">
        <!-- Boucle pour afficher les enfants -->
        @foreach($enfants as $key => $enfant)
        <a href="{{ route('welcome') }}" class="m-8">
            <div class="bg-orange shadow-lg  xl:p-24 rounded-full  border border-black xs:p-10">
                <div class="flex flex-col items-center">
                    @if($enfant->avatar)
                    <img src="{{ asset($enfant->avatar->fichier) }}" alt="Avatar de l'enfant"
                        class="xl:w-36 xl:h-36 rounded-full xs:w-20 xs:h-20">
                    @else
                    <span class="w-32 h-32 bg-gray-300 rounded-full flex items-center justify-center text-lg">Image non
                        disponible</span>
                    @endif
                    {{-- <p class="text-sm text-gray-600">Parent: {{ $enfant->user->prenom }}</p>
                    --}}
                </div>
            </div>
            @if ($key == 0)
            <h2 class="mt-2 font-bold text-3xl"><span class="text-white">{{ $enfant->user->prenom_enfant }}
            </h2>
            @else
            <h2 class="mt-2 font-bold text-3xl"><span class="text-white">{{ $enfant->name }}</h2>
            @endif
        </a>

        @endforeach
        <a href="{{ route('enfant.create') }}">
            <div class="bg-blue-800 shadow-lg rounded-full xl:p-32 flex items-center justify-center border border-black xs:p-11">
                <img src="{{ asset('images/formes/plus.svg') }}"class="xs:w-20 xs:h-20">

            </div>
        </a>

    </div>

</div>

@endsection
@section('title', 'Enfants')

@section('body-class', 'bg-sky-600')

resources/views/enfants/show.blade.php
@extends('layouts.base')

@section('content')

<div class="container mx-auto px-4">
    <div class="max-w-2xl mx-auto mt-8">
        <div class="bg-white p-6 rounded-lg shadow">
            <h2 class="text-2xl font-bold mb-4">{{ $enfant->name }}</h2>
            <div class="mb-4">
                <div class="mb-4">
                    <img src="{{ asset($enfant->avatar->fichier) }}" alt="{{ $enfant->avatar->nom }}"
                        class="object-contain object-center h-20 w-20">
                </div>
            </div>
            <p class="text-gray-700 mb-2"><strong>Âge:</strong> {{ $enfant->age }}</p>

            <div class="mt-4">
                <a href="{{ route('enfant.edit', $enfant->id) }}"
                    class="inline-block bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg mr-2">Modifier</a>
                <form action="{{ route('enfant.destroy', $enfant->id) }}" method="POST" class="inline">
                    @csrf
                    @method('DELETE')
                    <button type="submit"
                        class="inline-block bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection
@section('title', 'Enfants')