routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\ControllerListe;
use App\Http\Controllers\DesignSystemController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\TypeRecipeController;

use App\Http\Controllers\EnfantController;
use App\Http\Controllers\EtapeController;


use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/dashboard', function () {
    return redirect()->route('profile.edit');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::resource('type_recipe', TypeRecipeController::class);


Route::resource('recipe', RecipeController::class);


Route::resource('designsystem', DesignSystemController::class);

Route::resource('contact', ContactController::class);





Route::middleware('auth')->group(function () {
    Route::resource('enfant', EnfantController::class);
    Route::resource('etape', EtapeController::class);
    //Route::post('/etape/{id}', [EtapeController::class, 'show']);

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';

app/Models/Recipe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    use HasFactory;


    protected $table = 'recipes';

    protected $fillable = [
        'name','description','image', 'rating','temps_prepartion','types_recipes_id'
    ];

    public function typeRecipe(){
        return $this->belongsTo(TypeRecipe::class, 'types_recipes_id');
    }


    public function liaison_ustensils_recipes(){
        return $this->hasMany(Liaison_recipe_ustensil::class);
    }
    public function ingredientRecipes(){
        return $this->hasMany(Ingredient::class);
    }

    public function recipesEtapes(){
        return $this->hasMany(Etape::class);
    }
}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;
use App\Models\Recipe;

use App\Models\TypeRecipe;

use Illuminate\Http\Request;
use App\Http\Requests\RecipeRequest;


class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        $recipes =  Recipe::paginate(5);

        return view('recipes.index', ['recipes' => $recipes]);
         
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('recipes.create',['types_recipes' => TypeRecipe::all()]);

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(RecipeRequest $request)
    {

        Recipe::create($request->validated());


        return redirect()->route('recipe.index')
        ->with('ok', __('Recipe has been saved'));
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $recipe = Recipe::findOrFail($id);
        $etapes = \DB::table('etapes')
            ->where('recipe_id','=',$recipe->id)
            ->orderBy('ordre', 'asc')
            ->limit(1)
            ->get()
        ;
        $premiere_etape = $etapes[0] ?? null;

        return view('recipes.show', ['recipe' => $recipe, 'premiere_etape' => $premiere_etape]);
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Recipe $recipe)
    {
        return view('recipes.edit', ['recipe' => $recipe]);
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(RecipeRequest $request, Recipe $recipe)
    {
        $recipe->update( $request->all() );   
        return redirect()->route('recipe.index')
                         ->with( 'ok', __('Recipe has been updated') );
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Recipe $recipe)
    {
       $recipe->delete();
       return response()->json();
    }

}

resources/views/recipes/create.blade.php
<form method="POST" action="{{ route('recipe.store') }}">
        {{ csrf_field() }}
        <p>
                <label for="name">Nom recette</label>
                <input type="text" name="name" id="name" value="" required />
        </p>
        <p>
                <label for="description">Description</label>
                <input type="text" name="description" id="description" value="" required />
        </p>
        <p>
                <label for="image">image URL</label>
                <input type="text" name="image" id="image" value="" required />

        </p>
        <p>
                <label for="types_recipes_id">Type de plat</label>
                <select name="types_recipes_id" id="types_recipes_id" required>
                        @foreach($types_recipes as $type)
                        <option value="{{ $type->id }}">
                                {{ $type->name }}
                        </option>
                        @endforeach
                </select>
        </p>

        <p>
                <label for="rating">Rating (max 5)</label>
                <select name="rating" id="rating" required>
                        @for($i = 0.5; $i <= 5; $i +=0.5) <option value="{{ $i }}">{{ $i }}</option>
                                @endfor
                </select>
        </p>
        <p>
                <label for="temps_prepartion">Temps de préparation  </label>
                <input type="text" name="temps_prepartion" id="temps_prepartion" value="" required />

        </p>




        <button type="submit">Ajouter la recette</button>
</form>

resources/views/recipes/edit.blade.php
<form method="POST" action="{{ route('recipe.update', $recipe->id) }}">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <p>
                <label for="titre">{{ __('Titre') }}</label>
                <input type="text" name="titre" id="titre" value="{{ $recipe->titre }}" required />
        </p>
        <p>
                <label for="description">{{ __('Description') }}</label>
                <input type="text" name="description" id="description" value="{{ $recipe->description }}" required />
        </p>
        <p>
                <label for="difficulte">{{ __('Difficulte') }}</label>
                <input type="text" name="difficulte" id="difficulte" value="{{ $recipe->difficulte }}" required />
        </p>

        <p>
                <label for="ingredients">{{ __('Ingredients') }}</label>
                <input type="text" name="ingredients" id="ingredients" value="{{ $recipe->ingredients }}" required />
        </p>

        <p>
                <label for="ustensils">{{ __('Ustensils') }}</label>
                <input type="text" name="ustensils" id="ustensils" value="{{ $recipe->ustensils }}" required />
        </p>
        <p>
                <label for="temps_preparation">{{ __('Temps_preparation') }}</label>
                <input type="text" name="temps_preparation" id="temps_preparation" value="{{ $recipe->temps_preparation }}" required />
        </p>
        <p>
                <label for="image">{{ __('Image') }}</label>
                <input type="text" name="image" id="image" value="{{ $recipe->image }}" required />
        </p>

        <p>
                <label>{{ __('Plat sucré') }}</label>
                <input type="radio" name="plat_sucre" id="plat_sucre_oui" value="oui" {{ $recipe->plat_sucre === 'oui' ? 'checked' : '' }}>
                <label for="plat_sucre_oui">{{ __('Oui') }}</label>
        
                <input type="radio" name="plat_sucre" id="plat_sucre_non" value="non" {{ $recipe->plat_sucre === 'non' ? 'checked' : '' }}>
                <label for="plat_sucre_non">{{ __('Non') }}</label>
            </p>
        
       
        <button type="submit">Valider</button>
</form>

resources/views/recipes/index.blade.php
@extends('layouts.base')

@section('content')

<div class="flex justify-center">
    <h1 class="text-3xl font-bold my-8 text-white">Nos recettes sucrée ou salées</h1>
</div>

<div class="flex flex-row flex-wrap justify-center overflow-x-auto">
    @foreach ($recipes as $recipe)
    <a href="{{ route('recipe.show', $recipe->id) }}" class="m-4">
        <div class=" rounded-lg p-6 fondcard" style="min-width: 300px;">
            <h2 class="text-2xl font-bold mb-2 text-gray-800 text-center">{{ $recipe->name }}</h2>
            <img src="{{ $recipe->image }}" alt="Image de {{ $recipe->titre }}" class="w-full h-48 object-cover mb-4 rounded-lg">
            <div class="  h-36 flex gap-20 items-center">
                @php
                $rating = $recipe->rating;
                if ($rating >= 1 && $rating <= 2.5) { echo ' <p class="purple-star">★</p>' ; }
                elseif ($rating>=
                    2.6 && $rating <= 3.9) {
                        echo '<p class="purple-star text-5xl">★★</p>' ; }
                elseif
                        ($rating>= 4 && $rating <= 5) {
                            echo ' <p class="purple-star ">★★★</p>'
                            ; }
                @endphp
                <div class="flex items-center bg-bleu rounded-xl px-1">
                    <img class="w-9 h-9" src="{{ asset('images/formes/alarm.svg') }}"><span
                        class="font-semibold text-white">{{
                            $recipe->temps_prepartion }} min.</span>
                </div>
            </div>
        </div>
    </a>
@endforeach
</div>

{{-- <div class="flex justify-center mt-4">
    <div class="bg-blue-200 w-52 rounded-md text-center py-1 font-bold">
        <a href="{{ route('recipe.create') }}">
            {{ __('Ajouter une recette') }}
        </a>
    </div>
</div> --}}
<style>
    .fondcard{
        background-image: url("https://raw.githubusercontent.com/Niwa-Yume/image-worshop/main/post-it%20(1).svg");
        background-size: contain;
        background-repeat: no-repeat; /* Évite la répétition du fond */
        background-position: center;
    }
    
</style>
@endsection
@section('body-class', 'bg-sky-600')

resources/views/recipes/show.blade.php
@extends('layouts.base')

@section('content')

<p class="md:text-3xl xl:text-4xl font-bold my-8 text-center mt-60 xs:text-3xl xs:mt-36 sm:mt-36 md:mt-32 xl:mt-60">Ma
    liste de courses :</p>
<div
    class="flex  items-center justify-center gap-8  xs:flex-col sm:flex-col md:flex-row lg:flex-row xl:flex-row xxl:flex-row xxxl:flex-row xl:pb-10">
    <a href="{{ route('type_recipe.show', $recipe->typeRecipe->id) }}"
        class="hover:text-blue-600 flex flex-col  font-bold self-end xs:self-center sm:self-center md:self-end xs:order-3 sm:order-3 md:order-1 xl:order-1"><img
            class="w-24" src="{{ asset('images/formes/fleche_precedent.svg') }}"><span class="text-sm">Revenir au
            {{$recipe->typeRecipe->name}}</span>
    </a>
    <!-- Section des ingrédients -->
    <div class="xs:w-10/12	 max-w-md  bg-cover flex flex-col xs:order-1"
        style="background-image: url('/images/formes/liste.svg');">
        <p class="xs:text-xl xl:text-2xl font-bold  text-center mt-28 mb-4">Ingrédients :</p>

        <!-- Boucle pour afficher les ingrédients -->
        <div class="flex flex-col">
            @foreach($recipe->ingredientRecipes as $ingredient)
            <div class="flex items-center  justify-between  mb-2 ml-4">
                <div class="flex items-center"><input type="checkbox" name="ingredients[]" value="{{ $ingredient->id }}" class="mr-2  rounded-sm  w-6 h-6">
                    <span class="xs:font-medium xl:text-xl">{{ $ingredient->productIngredient->name }} {{ $ingredient->quantity }} {{
                        $ingredient->uniteIngredient->name }}</span>
                </div>
                <img class="h-16 mr-3" src="{{ $ingredient->productIngredient->image }}"
                    alt="{{ $ingredient->productIngredient->name }}">

            </div>

            @endforeach
        </div>
    </div>


    <!-- Section des ustensiles -->
    <div class="w-10/12	 max-w-md  bg-cover min-h-96 flex flex-col xs:order-2"
        style="background-image: url('/images/formes/liste.svg');">
        <p class="xs:text-xl xl:text-2xl font-bold  text-center mt-28  ">Ustensiles :</p>

        <!-- Boucle pour afficher les ustensiles -->
        @foreach($recipe->liaison_ustensils_recipes as $liaison)
        <div class="flex items-center  justify-between  mb-2 ml-4">
            <div class="flex items-center"><input type="checkbox" name="ustensils[]" value="{{ $liaison->ustensil->id }}" class="mr-2 rounded-sm w-6 h-6">
                <span class="xs:font-medium xl:text-xl">{{ $liaison->ustensil->name }}</span>
            </div>
            <img class="h-16 rounded-md  mr-3" src="{{ $liaison->ustensil->image }}"
                alt="{{ $liaison->ustensil->name }}">
        </div>
        @endforeach
    </div>
    @if ($premiere_etape)
    <a href="{{ route('etape.show', $premiere_etape->id) }}"
        class="hover:text-blue-600 flex flex-col  font-bold self-end xs:order-4 xs:self-center sm:self-center md:self-end"><img
            class="w-24" src="{{ asset('images/formes/fleche_suivant.svg') }}"><span class="text-sm">Étape
            suivante</span>
    </a>
    @else
    <p>On ne peut pas commencer!!!</p>
    @endif
</div>



@endsection
@section('body-class', 'bg-newJaune')
@section('background-image')
@section('title', 'Recettes')
<style>
    body {
        background-image: url('/images/formes/bg-liste.svg');
        background-size: cover;
        background-repeat: no-repeat;

    }

    @media (max-width: 800px) {
        body {
            background-image: url('/images/formes/bg-liste-mobile.svg');
        }
    }

    @media (max-width: 460px) {
        body {
            background-image: url('/images/formes/bg-liste-mobile-sans-bonhomme.svg');
        }
    }
</style>
@endsection