routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\ControllerListe;
use App\Http\Controllers\DesignSystemController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\TypeRecipeController;

use App\Http\Controllers\EnfantController;
use App\Http\Controllers\EtapeController;


use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/dashboard', function () {
    return redirect()->route('profile.edit');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::resource('type_recipe', TypeRecipeController::class);


Route::resource('recipe', RecipeController::class);


Route::resource('designsystem', DesignSystemController::class);

Route::resource('contact', ContactController::class);





Route::middleware('auth')->group(function () {
    Route::resource('enfant', EnfantController::class);
    Route::resource('etape', EtapeController::class);
    //Route::post('/etape/{id}', [EtapeController::class, 'show']);

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';

app/Models/Etape.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Etape extends Model
{
    use HasFactory;

    protected $fillable = [
        'titre','instruction','ordre','besoin_code_parental','recipe_id','fichier'
    ];

    public function etapeRecipe(){
        return $this->belongsTo(Recipe::class, 'recipe_id');
    }
}

app/Http/Controllers/EtapeController.php
<?php

namespace App\Http\Controllers;
use App\Models\Recipe;
use App\Http\Requests\EtapeRequest;

use App\Models\Etape;
use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class EtapeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        throw new NotFoundHttpException();
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('etape.create',['recipe_id' => Recipe::all()]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(EtapeRequest $request)
    {
        //
        Etape::create($request->validated());


        return redirect()->route('recipe.index')
        ->with('ok', __('etape has been saved'));
    }


    private function showEtapePage(Etape $etape, $codeByUser){

        //
        $recipe = $etape->etapeRecipe;

        $etape_precedente = Etape::where('recipe_id', '=', $recipe->id)
                              ->where('ordre', '<', $etape->ordre)
                              ->orderByDesc('ordre')
                              ->first();


        $askForCode = $etape->besoin_code_parental;
        if($askForCode){

            if($codeByUser){

                $user = auth()->user();

                if($codeByUser == $user->code_parental){
                    $askForCode = false;
                }
            }

        }

        $prochaine_etapes = \DB::table('etapes')
            ->where('recipe_id','=',$recipe->id)
            ->where('ordre', '>', $etape->ordre)
            ->orderBy('ordre', 'asc')
            ->limit(1)
            ->get()
        ;

        $prochaine_etape = $prochaine_etapes[0] ?? null;


        return view('etape.show', [
            'recipe' => $recipe,
            'etape' => $etape,   
            'askForCode' => $askForCode,
            'etape_precedente' => $etape_precedente,
            'prochaine_etape' => $prochaine_etape
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(Etape $etape)
    {
        return $this->showEtapePage($etape,'');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Etape $etape)
    {
        return $this->showEtapePage($etape, $request->request->get('code'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/etape/create.blade.php
@extends('layouts.base')
@section('content')

<form method="POST" action="{{ route('etape.store') }}">
        {{ csrf_field() }}
        <p>
                <label for="titre">Titre étape</label>
                <input type="text" name="titre" id="titre" value="" required />
        </p>
        <p>
                <label for="instruction">Instruction</label>
                <input type="text" name="instruction" id="instruction" value="" required />
        </p>
        <p>
                <label for="ordre"> Ordre</label>
                <input type="text" name="ordre" id="ordre" value="" required />

        </p>
        <p>
                <label for="fichier"> fichier chemin</label>
                <input type="text" name="fichier" id="fichier" value="" required />

        </p>
        <p>
                <label for="recipe_id">Recette</label>
                <select name="recipe_id" id="recipe_id" required>
                        @foreach($recipe_id as $recipe)
                        <option value="{{ $recipe->id }}">
                                {{ $recipe->name }}
                        </option>
                        @endforeach
                </select>
        </p>
        <p>
                <label for="besoin_code_parental">Besoin de code parental</label>
                <input type="checkbox" name="besoin_code_parental" id="besoin_code_parental" value="1">
        </p>







        <button type="submit">Ajouter cette étape</button>
</form>
@endsection

resources/views/etape/show.blade.php
@extends('layouts.base')

@section('content')
<div class="min-h-100 flex flex-col justify-center items-center p-4">

    @if ($askForCode)
    @section('body-class', 'bg-rouge')
    <div class="felx flex-col">
        <div class="flex items-center justify-center mb-8">
            <img class="w-20 h-20" src="{{ asset('images/formes/warning.svg') }}">
            <p class="text-white xs:text-2xl md::text-4xl font-bold text-center">Appelle un adulte pour cette étape !</p>
        </div>
        <form id="parental_code_form" method="POST"
            class="bg-white p-12 px-36 rounded-3xl flex border border-black xs:p-0 sm:p-0 md:p-3">
            {{ csrf_field() }}
            {{ method_field('PUT')}}
            <div class="flex flex-col gap-6 w-full items-center">
                <div class="flex flex-col items-center">
                    <label for="password" class="text-rouge text-2xl font-extrabold text-center pb-2">Code
                        parental</label>
                    <div class="flex gap-3">
                        <input type="password" name="code_part_1" id="code_part_1"
                            class="bg-rouge rounded-md w-12 text-center text-white text-3xl" maxlength="1"
                            pattern="[0-9]" title="Entrez un chiffre" autofocus/>
                        <input type="password" name="code_part_2" id="code_part_2"
                            class="bg-rouge rounded-md w-12 text-center text-white text-3xl" maxlength="1"
                            pattern="[0-9]" title="Entrez un chiffre" />
                        <input type="password" name="code_part_3" id="code_part_3"
                            class="bg-rouge rounded-md w-12 text-center text-white text-3xl" maxlength="1"
                            pattern="[0-9]" title="Entrez un chiffre" />
                        <input type="password" name="code_part_4" id="code_part_4"
                            class="bg-rouge rounded-md w-12 text-center text-white text-3xl" maxlength="1"
                            pattern="[0-9]" title="Entrez un chiffre" />
                    </div>
                </div>

                <input type="hidden" name="code" id="code" />

                <button class="py-2 w-2/3 bg-bleuNav text-white text-xl font-bold rounded-xl border border-black"
                    type="submit">Valider</button>
            </div>
        </form>
        @if ($etape_precedente)
        <a href="{{ route('etape.show', $etape_precedente->id) }}"
            class="hover:text-blue-600 flex flex-col self-start pt-5 font-bold">
            <img src="{{ asset('images/formes/fleche_precedent.svg') }}" alt="Étape précédente" class="w-24">
            <span class="text-sm">Étape précédente</span>
        </a>
        @else
        <a href="{{ route('recipe.show', $recipe->id) }}" class="hover:text-blue-500 flex flex-col pt-5 font-bold">
            <img src="{{ asset('images/formes/fleche_precedent.svg') }}" alt="Retour à la recette" class="w-24">
            <span class="text-sm">Retour à la recette</span>
        </a>
        @endif

        <script>
            function moveFocus(input, next) {
    var maxLength = parseInt(input.getAttribute('maxlength'));
    if (input.value.length >= maxLength && next) {
        next.focus();
    }
}

document.addEventListener('DOMContentLoaded', function () {
    var inputs = document.querySelectorAll('input[type="password"][name^="code_part_"]');
    
    inputs.forEach(function (input, index) {
        input.addEventListener('keyup', function (event) {
            moveFocus(input, index < inputs.length - 1 ? inputs[index + 1] : null);
        });
    });
});
            document.getElementById('parental_code_form').addEventListener('submit', function() {
            var code = document.getElementById('code_part_1').value +
                       document.getElementById('code_part_2').value +
                       document.getElementById('code_part_3').value +
                       document.getElementById('code_part_4').value;
    
            document.getElementById('code').value = code;
        });
        </script>

    </div>
    @else


    <div
        class="w-full max-w-2xl flex flex-col items-center space-y-6 bg-yellow-300 rounded-lg shadow-lg p-6  border border-black">

        <h1 class="text-4xl font-bold text-center">{{ $recipe->name }} - Étape {{ $etape->ordre }}</h1>

        <video id="myVideo" class="rounded-lg w-full h-auto bg-bleu" controls  autoplay>
            <source src="{{ asset($etape->fichier) }}" type="video/mp4">
            Votre navigateur ne supporte pas les vidéos au format MP4.
        </video>

        <div class="w-full xs:flex-col  md:flex md:flex-row  justify-between items-center xs:space-x-0 xl:space-x-4">
            @if ($etape_precedente)
            <a href="{{ route('etape.show', $etape_precedente->id) }}"
                class="hover:text-blue-600 flex flex-col items-center font-bold">
                <img src="{{ asset('images/formes/fleche_precedent.svg') }}" alt="Étape précédente" class="xs:w-12 xl:w-24">
                <span class="xs:text-xs xl:text-sm">Étape précédente</span>
            </a>
            @else
            <a href="{{ route('recipe.show', $recipe->id) }}"
                class="hover:text-blue-600 flex flex-col items-center font-bold">
                <img src="{{ asset('images/formes/fleche_precedent.svg') }}" alt="Retour à la recette" class="xs:w-12 xl:w-24">
                <span class="xs:text-xs xl:text-sm">Retour à la recette</span>
            </a>
            @endif

            <div class="flex-1 xs:m-0 xl:mx-4 text-center bg-gray-100 xs:p-1 xl:p-4 rounded-lg border border-black">
                <p class="text-lg">{{ $etape->instruction }}</p>
            </div>

            @if ($prochaine_etape)
            <a href="{{ route('etape.show', $prochaine_etape->id) }}"
                class="hover:text-blue-600 flex flex-col items-center font-bold">
                <img src="{{ asset('images/formes/fleche_suivant.svg') }}" alt="Étape suivante" class="xs:w-12 xl:w-24">
                <span class="xs:text-xs xl:text-sm">Étape suivante</span>
            </a>
            @else
            <p class="text-sm">C'est fini</p>
            @endif
        </div>
    </div>
    @endif
</div>

@endsection
@section('title', 'Étapes')

@section('body-class', 'bg-jauneEtape')